add description and parameterize email and access key

diff --git a/src/orb.yml b/src/orb.yml
--- a/src/orb.yml
+++ b/src/orb.yml
@@ -1,60 +1,71 @@
 version: 2.1
-description: >
-  Encapsulates interactions with LambdaTest tunnel.
+description: |
+      Seamlessly integrate Lambda Tunnel with CircleCI pipelines and 
+      run Selenium tests on 2000+ browsers for your locally hosted or 
+      privately hosted pages with LambdaTest Selenium Grid.
 display:
   home_url: https://www.lambdatest.com/
   source_url: https://github.com/LambdaTest/Lambdatest-circleci-orb
 
 commands:
   install:
+    description: |
+      Launches the tunnel binary in background
     steps:
       - run: 
-          name: "Downloading tunnel binary"
+          name: "Download and Extract tunnel binary"
           command: |
-            sudo apt-get update && sudo apt-get install -y curl unzip ucommon-utils psmisc
+            sudo apt-get update && sudo apt-get install -y curl unzip iproute2 psmisc
             curl -O https://downloads.lambdatest.com/tunnel/linux/64bit/ltcomponent.zip
-      
-      - run: 
-          name: "Extracting tunnel binary"
-          command: |
             unzip ltcomponent.zip
             mv ltcomponent LT
             chmod +x LT
             rm ltcomponent.zip
 
   open_tunnel:
+    description: |
+        Launches the tunnel binary in background
     parameters:
+      lambdatest_email:
+        description: Specify your LambdaTest email
+        type: string
+      lambdatest_key:
+         description: Specify your LambdaTest Access Key
+         type: env_var_name
+         default: LAMBDATEST_KEY
       tunnel_name:
-        description: This feature will help you use the available tunnels from the selected head account which is the main account for performing parallel tunnel testing. While using this feature you are required to select both tunnel name and head tunnel.
+        description: Specify a tunnel name to uniquely identify your tunnel on LambdaTest platform
         type: string
         default: ""
       shared_tunnel:
-        description: Sharing tunnel among team members <<Optional>>
+        description: Sharing tunnel among team members
         type: boolean
         default: false
       proxy_host:
-        description: Specify Proxy Host <<Optional>>
+        description: You may specify a proxy host if connecting tunnel via proxy
         type: string
         default: ""
       proxy_port:
-        description: Specify Proxy Port <<Optional>>
+        description: You may specify a proxy port if connecting tunnel via proxy
         type: string
         default: ""
       proxy_user:
-        description: Specify Proxy Username <<Optional>>
+        description: You may specify a proxy username if connecting tunnel via proxy that has authentication enabled
         type: string
         default: ""
       proxy_pass:
-        description: Specify Proxy Password <<Optional>>
+        description: You may specify a proxy password if connecting tunnel via proxy that has authentication enabled
         type: string
         default: ""
     steps:
       - run: 
-          name: "Executing tunnel binary"
+          name: "Executing the tunnel binary"
           background: true
           command: |
-            : ${LAMBDATEST_EMAIL:?"Required Env Variable - LAMBDATEST_EMAIL not found!"}
-            : ${LAMBDATEST_KEY:?"Required Env Variable - LAMBDATEST_KEY not found!"}
+            if [ -z "$<<parameters.lambdatest_key>>" ]; then
+              echo "Error: The parameter lambdatest_key is empty. Please ensure the environment variable LAMBDATEST_KEY has been added."
+              exit 1
+            fi
             read LOWERPORT UPPERPORT < /proc/sys/net/ipv4/ip_local_port_range
             PORT=$LOWERPORT
             while [  $PORT -lt $UPPERPORT ]; do
@@ -62,7 +73,7 @@ commands:
                 let PORT=PORT+1 
             done
             echo "$PORT" > /tmp/port
-            ./LT --user ${LAMBDATEST_EMAIL} --key ${LAMBDATEST_KEY} --controller circleci --infoAPIPort $PORT \
+            ./LT --user <<parameters.lambdatest_email>> --key ${<<parameters.lambdatest_key>>} --controller circleci --infoAPIPort $PORT \
             <<# parameters.tunnel_name >> --tunnelName <<parameters.tunnel_name>> \
             <</ parameters.tunnel_name>>
             <<# parameters.proxy_host >> --proxy-host <<parameters.proxy_host>> \
@@ -76,15 +87,19 @@ commands:
             <<# parameters.shared_tunnel >> --shared-tunnel \ <</ parameters.shared_tunnel>>
             /
   wait_tunnel:
+    description: |
+      Waits for the tunnel connection to be established with the tunnel server
     steps:
       - run:
           name: Wait for LambdaTest Tunnel
           command: |
-            while [ ! -f /tmp/port ]; do sleep 1; done
+            while [ ! -f /tmp/port ]; do sleep 0.5; done
             PORT=$(head -1 /tmp/port)
-            curl --silent --connect-timeout 5 --max-time 5 --retry 30 --retry-delay 2 --retry-max-time 60 http://127.0.0.1:$PORT/api/v1.0/info 2>&1 > /dev/null
+            curl  --silent --retry-connrefused --connect-timeout 5 --max-time 5 --retry 30 --retry-delay 2 --retry-max-time 60 http://127.0.0.1:$PORT/api/v1.0/info 2>&1 > /dev/null
 
   close_tunnel:
+    description: |
+      Quitting the tunnel after test suite has been run
     steps:
       - run:
           name: Close LambdaTest Tunnel
@@ -97,33 +112,40 @@ commands:
             rm /tmp/port
 jobs:
   with_tunnel:
-    description: Start LambdaTest Tunnel
+    description: Job to run LambdaTest tunnel for testing locally or privately hosted web apps
     parameters:
       docker:
         type: string
-        default: "circleci/node:8.9.4"
+        default: "cimg/node:current"
+      lambdatest_email:
+        description: Specify your LambdaTest email
+        type: string
+      lambdatest_key:
+         description: Specify your LambdaTest Access Key
+         type: env_var_name
+         default: LAMBDATEST_KEY
       tunnel_name:
-        description: Name your lambda tunnel and make sure to use this tunnel_name desired capability in your test <<Optional>>
+        description: Specify a tunnel name to uniquely identify your tunnel on LambdaTest platform
         type: string
         default: ""
       shared_tunnel:
-        description: Sharing tunnel among team members <<Optional>>
+        description: Sharing tunnel among team members
         type: boolean
         default: false
       proxy_host:
-        description: Specify Proxy Host <<Optional>>
+        description: You may specify a proxy host if connecting tunnel via proxy
         type: string
         default: ""
       proxy_port:
-        description: Specify Proxy Port <<Optional>>
+        description: You may specify a proxy port if connecting tunnel via proxy
         type: string
         default: ""
       proxy_user:
-        description: Specify Proxy Username <<Optional>>
+        description: You may specify a proxy username if connecting tunnel via proxy that has authentication enabled
         type: string
         default: ""
       proxy_pass:
-        description: Specify Proxy Password <<Optional>>
+        description: You may specify a proxy password if connecting tunnel via proxy that has authentication enabled
         type: string
         default: ""
       steps:
@@ -135,6 +157,8 @@ jobs:
       - checkout
       - install
       - open_tunnel:
+          lambdatest_email: <<parameters.lambdatest_email>>
+          lambdatest_key: <<parameters.lambdatest_key>>
           tunnel_name: <<parameters.tunnel_name>>
           shared_tunnel: <<parameters.shared_tunnel>>
           proxy_host: <<parameters.proxy_host>>
